### ISSUE TITLE
Possible sam header conversion in sam_to_pre when working with 3d-DNA

### ISSUE THREAD

**Issue by DustinSokolowski** [theaidenlab/3d-dna#132]
Hey Olga and Neva!

Thank you again for your wonderful tools. I've been using Juicer-2.0 to try and assemble a _de novo_ genome and compare the scaffolding of salsa2+JBAT and 3dDNA+JBAT. To do this, I have used the sam_to_pre script to generate the merged_nodups file needed for 3dDNA and then JBAT but I think some sam file headers are getting messed up. The primary error is shown below. 

![image](https://user-images.githubusercontent.com/56414662/134817140-72adb2f2-56e2-4467-9304-05579a3e5b92.png)

I looked into this error and the closest thing I can post is from 2018, were it looks like some of the sam headers weren't properly getting converted from the original merged_nodups file and as such chromosomes won't get properly recognized:
https://groups.google.com/g/3d-genomics/c/UB2-LVp2foY/m/AT6zw7kgCQAJ

I have two biological replicates which each work fine, but when I combine them at the fastq (with cat), bam (with samtools), or merged_nodups (with mega.sh) level, I find that this error reoccurs. Plotting the combined Hi-C files also leads to some missing chromsomes. 

![image](https://user-images.githubusercontent.com/56414662/134817253-9f572334-2bbb-4e04-a6b3-556fb8ace8c2.png)

Below is an example of when I combined the replicates at the fastq level (with cat) and then ran everything more or less normally.

![image](https://user-images.githubusercontent.com/56414662/134817342-4912f88f-ed57-4496-8528-3583874bf7a4.png)

I've attached a heatmap of me doing this before with an individual replicate to show that it does work on my system normally, and something funny is happening with the merging of replicates.

If you have any advice and if you have the time to check and make sure everything with the sam_to_pre script is normal then I'd greatly appreciate it!

Best,
Dustin

**Comment by dudcha** [comment]
Hi Dustin,

sam_to_pre script is not part of 3D-DNA: closing this complaint here, but will try to pass along. The image suggests to me that something goes wrong with restriction fragment assignment.

Thanks,
Olga
