### ISSUE TITLE
what's the genome for run-asm-pipeline-post-review.sh

### ISSUE THREAD

**Issue by yywyaoyaowu** [theaidenlab/3d-dna#133]
when I use "run-asm-pipeline-post-review.sh" to get the final sequence after using juice box. 
path_to_input_fasta, what's the genome? the original genome, or the *final.fasta generated by 3d-DNA?  Thanks very much! 

But I met an warning “:| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
:| Warning: No input for label2 was provided. Default for label2 is ":::debris"”,.

**Comment by dudcha** [comment]
Hi,

It’s the original fasta.

Olga
