### ISSUE TITLE
Truncated fasta headers

### ISSUE THREAD

**Issue by aakashsur** [theaidenlab/3d-dna#139]
I noticed that 3d-dna truncates the fasta headers at the first whitespace. 

So `OMLG01037572.1 Thunnus albacares genome assembly, contig: scf7180003985869, whole genome shotgun sequence` becomes `OMLG01037572.1`. 

This introduces the extra step of truncating headers when matching fasta sequences to the assembly file.

**Comment by dudcha** [comment]
3D-DNA follows an NCBI-style convention and expects the description line to be of the form >SeqID where sequin is unique. Additional information in the description line is ignored.
Thanks, -Olga
