### ISSUE TITLE
how t speed running the run-asm-pipeline.sh

### ISSUE THREAD

**Issue by Aannaw** [theaidenlab/3d-dna#140]
Hello,everyone
I am running the `run-asm-pipeline.sh.` `My command is : /data/01/user157/software/3d-dna/run-asm-pipeline.sh -r 1  M.aspalax.6.bp.p_ctg.fasta merged_nodups.txt. `The `M.aspalax.6.bp.p_ctg.fasta` is from `Hifiasm assembly` and the `merged_nodups.txt `is from `juicer pipline. `I do not find the thread option in the` run-asm-pipeline.sh`, so I only set` 1 CPU and 250G memory` when I submit the  task by `SLURM. `My data size is much lager : the `merged_nodups.txt is 327G` and the  `M.aspalax.6.bp.p_ctg.fasta is 2.9G`. It has run for six days. But when I check the log file, it is running the step of` iterating scaffolding for round 0`. Is it correct? And any idea to save the time? Maybe should I  increase the `CPU` setting?
Could you give me any suggestions?
Best wishes!
[3ddna.log](https://github.com/aidenlab/3d-dna/files/8078956/3ddna.log)

**Comment by Jinke233** [comment]
My condition is the same as yours!  Did you solve it?

**Comment by dudcha** [comment]
I believe I answered this already on the forum. Please post on the forum (aidenlab.org/forum.html). Thanks!

**Comment by Jinke233** [comment]
Thank your answer! I had changed the default parameter "--jobs 30&nbsp; --block 1G" . Is this parameter proper?&nbsp; I found the loading rate of every cpu does not up to 100%. What's your parameter? By the way, I noticed your mnd.txt is&nbsp; two times larger&nbsp; than my file, So how much did you spend ?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aidenlab/3d-dna"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 凌晨4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aidenlab/3d-dna] how t speed running the run-asm-pipeline.sh (Issue #140)





 
Closed #140.
