### ISSUE TITLE
HiFi and Nanopore behave differently in 3D DNA (due to different draft assembly sizes)

### ISSUE THREAD

**Issue by kuangzhuoran** [theaidenlab/3d-dna#141]
I have HiFi + HiC, Nanopore + HiC data
The draft assembly of HiFi was finished by Hifiasm,  draft assembly of Nanopore was finished by Nextdenova
The first is that the two sequencing methods, the resulting draft assemblies differ by about 600M. (HiFi : 3.1G, Nanopore: 2.5GM)

Based on such draft assembly, the size of the chromosome part finally obtained by HiFi and nanopore is the same (more than 2.4G)

I have 8 genomes,  2 are HiFi and 6 are Nanopore. The results are consistent with the above.
I can now determine that the chromosome size of my species is 2.4~2.5G，because the results for the eight genomes are the same

In the draft assembly, the extra 600M of HiFi is also the part that cannot be anchor on the chromosome. In the heat map, there is no interaction matrix in this part.

I think the extra 600M should be redundant and repetitive

HiFi + HiC   heatmap
![hifi](https://user-images.githubusercontent.com/76553133/155090600-cfbaf841-e85f-48e6-940d-0ac713bdf050.png)

Nanopore + HiC   heatmap
![ONT](https://user-images.githubusercontent.com/76553133/155090629-bf72c30b-689a-490a-970c-a26b625970f1.png)

**Comment by dudcha** [comment]
Closing since this seems to be a general comment rather than an issue. Indeed input data model and contigger will influence the output assembly. You can use Hi-C to recognize some of the associated error modalities.
Best,
Olga
