### ISSUE TITLE
I have assembled three genomes at the same time, and they have stayed in one place for a long time

### ISSUE THREAD

**Issue by kuangzhuoran** [theaidenlab/3d-dna#142]
But they seem to be running. Is that normal？
awk -f x.final.cprops draft.genome
awk -f x.rawchrom.cprops draft.genome

![cdceb98b50643f6eb817241954d3a4d](https://user-images.githubusercontent.com/76553133/156140950-6cefd6da-859c-4725-8068-33264a6d00d8.png)

Then I checked the specific step
![f7dbdf2e71b743885981e3b118bc5f6](https://user-images.githubusercontent.com/76553133/156140961-3764e866-77d8-48a5-960a-08b167d4578b.png)

**Comment by dudcha** [comment]
Please see comments about wrapping your input fasta (utils/wrap-fasta-sequence.awk). Note that in latest release wrapping is done automatically. Best, -Olga
