### ISSUE TITLE
3d-dna/visualize/juicebox_tools.sh: line 3: 180724 be killed

### ISSUE THREAD

**Issue by xiaobaiymq** [theaidenlab/3d-dna#143]
Hello sir
 my command is “bsub -J 3d-dna -n 5 -R span[hosts=1] -o  %J.out -e %J.err -q q2680v2 "module purge ;module load BWA/0.7.17;run-asm-pipeline.sh   ../reference/nfmj.asm.hic.hap1.p_ctg.fa ../aligned/merged_nodups.txt"  ”

but err is：
/public/home/mqyin/app/3d-dna/visualize/juicebox_tools.sh: 行 3: 180724 已杀死               java -Xms49152m -Xmx49152m -jar `dirname $0`/juicebox_tools.jar $*
Unable to dump
java.io.IOException: Normalization missing for: assembly_assembly_BP_25000
        at juicebox.data.DatasetReaderV2.readNormalizedBlock(DatasetReaderV2.java:719)
        at juicebox.data.MatrixZoomData.dump(MatrixZoomData.java:675)
        at juicebox.tools.clt.old.Dump.dumpMatrix(Dump.java:282)
        at juicebox.tools.clt.old.Dump.run(Dump.java:505)
        at juicebox.tools.HiCTools.main(HiCTools.java:86)
已终止

I don't know why，can you help me ?

**Comment by dudcha** [comment]
This suggest that the code wasn't able to build a normalization vector for your hic file. Usually this means that there are some big coverage issues, e.g. due the presence of non-nuclear contaminants, alt haplotypes, other. You can try to pass --editor_coarse_norm NONE when running run-3ddna-pipeline.sh. Best, -Olga

**Comment by kedduck** [comment]
> This suggest that the code wasn't able to build a normalization vector for your hic file. Usually this means that there are some big coverage issues, e.g. due the presence of non-nuclear contaminants, alt haplotypes, other. You can try to pass --editor_coarse_norm NONE when running run-3ddna-pipeline.sh. Best, -Olga

Dear developer 

I also meet the problem due to the haplotigs in the genome.

When I using the parameter "--editor_coarse_norm NONE", it just shows no this parameter. And I read the file "run-asm-pipeline.sh" , also not find the parameter "--editor_coarse_norm NONE", should I use  "--editor_coarse_resolution NONE" ? 

Expect for your relpy

Thanks a lot!

**Comment by xiaobaiymq** [comment]
Hello，
I have solved this problem.My error was because I first used the “--editor-repeat-coverage ”parameter，when I cancel this command and use the default parameters, everything becomes normal.

**Comment by kedduck** [comment]
@xiaobaiymq  Thank you!
