### ISSUE TITLE
MERGING step seems not using GNU parallel? 

### ISSUE THREAD

**Issue by wangc1106** [theaidenlab/3d-dna#145]
dear professor
i am using run-asm-pipeline.sh script in the GNU parallele obtained cluster.
at the biginning of the job, it speed up, but when it run the MERGING step(generate prefix.rawchrom.fasta), it is so slow, it only generate 117 Mb   .rawchrom.fasta file using 10 housrs, for my sample, the fasta may be 1.4 G, so it will use 100 hour+ in generating prefix.rawchrom.fasta step?
could you give me some advice,
thank you

**Comment by wangc1106** [comment]
Dear professor
before running  run-asm-pipeline.sh , i tried to use the wrao step to speed up the pipeline
```
awk /xtdisk/software/3d-dna-master/utils/wrap-fasta-sequence.awk HiFi.fa > HiFi.wrapped.fasta
```
bue the error happened

```
awk: cmd. line:1: /xtdisk/xueyb_group/wangchenA/software/3d-dna-master/utils/wrap-fasta-sequence.awk
awk: cmd. line:1:                                                                               ^ syntax error

```
could you give me some advice,
thank you

**Comment by dudcha** [comment]
Hi,

Please note that the diploid option is no longer supported. Are you sure you are referring to merging step? If you are referring to generating rawchrom.fasta in the haploid case please make sure that your fasta is wrapped (${pipeline}/utils/wrap-fasta-sequence.awk, done automatically in latest release, off the phasing branch). See more about this on aidenlab.org/forum.html.

Olga

**Comment by wangc1106** [comment]
Hi , professor Olga
i have solved the problem by running  
```
/software/3d-dna-master/run-asm-pipeline.sh \
-r 0 \
pathto/draft.wrapped.fasta \
pathto/aligned/merged_nodups.txt
```
thank you for your reply, i made a mistake, it was not the problem of merging step.

But now, i have a problem others mentioned before. #46 , #29 , #117 , #93 , #22 
```
tail: write error
tail: write error: Broken pipe
```
i still didnt solve the broken pipe error,
could give me some advice?
than you 
banner
