### ISSUE TITLE
link coverage file extraction 

### ISSUE THREAD

**Issue by chklopp** [theaidenlab/3d-dna#160]
Is there a way to extract a .bed or .wig coverage file from the .hic file?

**Comment by dudcha** [comment]
Yes, it's possible. Run smth like <path to juicebox> dump norm VC ${hic_file} assembly BP ${bin_size} "coverage_wide.wig"
Closing since this is not an issue report. Please consider using forum (aidenlab.org/forum.html) for inquiries.
Thanks, -Olga
