### ISSUE TITLE
HiC resolution issue: Unable to dump

### ISSUE THREAD

**Issue by AzumaSerenThePatriot** [theaidenlab/3d-dna#161]
I am working on a genome that is relatively large, and it takes too long time and storage to produce a .hic file with 1,000bp resolution. So I modified the resolution in _run-asm-pipeline.sh_:
"res_string="2500000,1000000,500000,250000,100000,50000,25000,10000"
And run the pipeline with the following:
run-asm-pipeline.sh --editor-fine-resolution 10000 --polisher-fine-resolution 10000 --splitter-fine-resolution 10000 genome.fa merged_nodups.txt

It succeeded. But as the resolution is lower, the debris region are a bit too long and thousands of annotated genes can not be mapped to the chromosome-scale genome. So I changed the resolution again into "res_string="2500000,1000000,500000,250000,100000,50000,25000,10000,2500" and ran the pipeline again, but it doesn't work anymore, with the following issues:

Unable to dump
java.io.IOException: Normalization missing for: assembly_assembly_BP_4166
        at juicebox.data.DatasetReaderV2.readNormalizedBlock(DatasetReaderV2.java:719)
        at juicebox.data.MatrixZoomData.dump(MatrixZoomData.java:675)
        at juicebox.tools.clt.old.Dump.dumpMatrix(Dump.java:282)
        at juicebox.tools.clt.old.Dump.run(Dump.java:505)
        at juicebox.tools.HiCTools.main(HiCTools.java:86)
Norm not available at BP_4166 VC
:( Juicebox coverage dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat ‘repeats_wide.bed’: No such file or directory
cat: repeats_wide.at.step.0.bed: No such file or directory
:( Annotations are our of range covered by suggested contigs. Exiting!

(The scale was 6 so 4166bp comes from 25000/6)
Can anyone help with this? Do the pipeline have to work with 10,000bp or 1,000bp .hic file?

**Comment by dudcha** [comment]
Hey,
I think I replied to this on the forum. Thanks,
Olga
