### ISSUE TITLE
How to obtain input mnd file from juicer2 output file？

### ISSUE THREAD

**Issue by XuanZhang-Black** [theaidenlab/3d-dna#164]
Hi! I ran juicer2 and produced the following files, there is no mnd file as 3d-dna input.I noticed that merged_nodups.txt has been replaced by the bam and merged*txt files in juicer2. But in 3d-dna's manual has not been updated. so how should I get merged_nodups.txt?  Thanks!
merged1.txt
merged30.txt,
merged_dedup.bam
inter.txt
inter_30.txt
inter.hic
inter_30.hic

**Comment by dudcha** [comment]
hi Xuan,

There is a --assembly filag you can include when running Juicer2 that will produce the standard mnd file.

Thanks,
Olga
