### ISSUE TITLE
temp. genome.0.asm _ mnd.txt does not exist or does not contain any reads

### ISSUE THREAD

**Issue by CuiYutong916** [theaidenlab/3d-dna#165]
When I run 3d-dna, the commands I run are as follows:
bash run-asm-pipeline.sh -q 1 -r 0 --editor-repeat-coverage 50 -e /my_path/genome.fa  /my_path/merged_nodups.txt
But the program did not generate hic file. Program error "temp. genome.0.asm _ mnd.txt does not exist or does not contain any reads." and stoped running

Starting iterating scaffolding with editing:
...starting round 0 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: genome.0.cprops
...Using merged_nodups file: genome.mnd.0.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
:) DONE!
...visualizing round 0 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
temp.genome.0.asm_mnd.txt does not exist or does not contain any reads.

**Comment by dudcha** [comment]
This suggests there is an inconsistency between your fasta file and the merged_nodups you are passing. Are you the merged_nodups was generated via alignment to this fasta? I suggest manually checking: go ahead and open the merged nodups file and look at the molecule names. DO they match those in the fasta? -Olga

**Comment by xingguowu** [comment]
hi, how do you deal with this error?
