### ISSUE TITLE
How to obtain a temporary gene.final.fasta?

### ISSUE THREAD

**Issue by XXH123a** [theaidenlab/3d-dna#166]
:) -c flag was triggered, will remove temporary files after completion

Dear developer,
        Excuse me, as shown above, how can I obtain  “. final.fasta“ without triggering the - c flag? I look forward to your guidance, thank you very much, and wish you all the best!

**Comment by dudcha** [comment]
Hello,

The message about temporary file after completion has nothing to do with the .final.fasta. Can you describe what exactly you are trying to do? Do you just want the edited file and not the final chromosome-length?

Olga

**Comment by XXH123a** [comment]
Wow, I'm honored to receive your response. I want to use run-asm-pipeline-post-review.sh to assemble the chromosome level .final.fasta of genome.0.assembly, but it is exactly the same as contig.fasta except for the addition of fragments_ 1:: Debris describes how to obtain chromosome level assembly results?

**Comment by dudcha** [comment]
I recommend looking through the Genome assembly cookbook hosted on dnazoo.org/methods. Post-review takes in an assembly file that describes the edits to the original contigs as well as ordering, orientation and anchoring of original contigs. It takes the pieces of the original sequences in required order, puts them together, adds gaps on between and dumps the resulting fasta (FINAL.fasta in previous releases, _HiC.fasta in the later releases). -OlgaOn Mar 20, 2023, at 11:41 AM, XXH123a ***@***.***> wrote:﻿
Wow, I'm honored to receive your response. I want to use run-asm-pipeline-post-review.sh to assemble the chromosome level .final.fasta of genome.0.assembly, but it is exactly the same as contig.fasta except for the addition of fragments_ 1:: Debris describes how to obtain chromosome level assembly results?

**Comment by XXH123a** [comment]
![dc7428284f6e187ae5b6e57a61f0614](https://user-images.githubusercontent.com/96107726/226412862-41180a33-7b69-4db1-a7f1-3904a9b9ab28.png)
Thank you very much. I saw the scaffold level results. I used HiFiasm to assemble a highly heterozygous 450M plant genome with 515 contigs. This. HiC.fasta shows 2003 scaffolds. I don't understand. It has seven chromosomes. Should I add the parameter - C 7?

**Comment by dudcha** [comment]
Please consider reading the cookbook. It will come in handy. You do not want to blindly take the fasta. You want to study the contact maps: they are there to help you with quality control. The number of scaffolds does not mean much. it is the distribution of sizes that is important. -Olga

**Comment by XXH123a** [comment]
Thank you again for your careful guidance. I just need to study Juicebox carefully now to obtain the results I need. I wish you a smooth work and a happy family.
